name: CD 
on:
  push: 
    branches:
      - main
      - release

  workflow_dispatch:
    
jobs: 
  CD:
    runs-on: ubuntu-latest

    steps:

      - name: Configure SSH Google Cloud
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/google-cloud.key
          chmod 600 ~/.ssh/google-cloud.key
          cat >>~/.ssh/config <<END
          Host google-cloud
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/google-cloud.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.GOOGLE_CLOUD_USER }}
          SSH_KEY: ${{ secrets.GOOGLE_CLOUD_SSH_KEY }}
          SSH_HOST: ${{ secrets.GOOGLE_CLOUD_HOST }}

      - name: checkout
        uses: actions/checkout@v2
      - name: Checkout correct branch
        run: |
          if [ "${{ github.ref }}" = "refs/heads/release" ]; then
            git checkout release
          else
            git checkout main
          fi
        working-directory: ${{ github.workspace }}

      - name: Configurando nodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: instalando dependencias
        run: npm install
      
      - name: Executando testes
        run: npm run test -- --coverage --passWithNoTests
        env:
          CI: true

      - name: executando sonar
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Buildando aplicacao
        run: npm run build

      - name: Deploy em produção
        if: github.ref == 'refs/heads/main'
        run: | 
          ssh google-cloud 'sudo systemctl stop react-app'
          ssh google-cloud 'sudo rm -rf /app/react-app'
          scp -r build google-cloud:/home/gitactions/react-app
          ssh google-cloud 'sudo mv /home/gitactions/react-app /app/react-app'
          ssh google-cloud 'sudo systemctl start react-app'

      - name: Deploy em homologação
        if: github.ref == 'refs/heads/release'
        run: | 
          ssh google-cloud 'sudo systemctl stop react-app-homolog'
          ssh google-cloud 'sudo rm -rf /app/react-app-homolog'
          scp -r build google-cloud:/home/gitactions/react-app-homolog
          ssh google-cloud 'sudo mv /home/gitactions/react-app-homolog /app/react-app-homolog'
          ssh google-cloud 'sudo systemctl start react-app-homolog'