name: CI

on:

  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs: 
  CI:
    runs-on: ubuntu-latest

    steps:

      - name: checkout
        uses: actions/checkout@v3

      - name: Configurando nodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: instalando dependencias
        run: npm install
      
      - name: Executando testes
        run: npm run test -- --coverage --passWithNoTests
        env:
          CI: true

      - name: executando sonar
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}